--
-- PostgreSQL database dump
--

\restrict ZIbt2GzRwbssAmEgBeYKEfELVWg6Sz3zFHdKJUGCyT23mP2C0GOGTLnNDAI5Hxa

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: __drizzle_migrations; Type: TABLE DATA; Schema: drizzle; Owner: postgres
--

INSERT INTO drizzle.__drizzle_migrations VALUES (1, '7b055d294dba93d99fcb952a851a48280acce62427fad3496ef4234e9c61aacc', 1774543661223);


--
-- Data for Name: recipes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.recipes VALUES (1, 'bruaca-cearense', false, 'bruaca', 'Bruaca cearense', 'Receita de bruaca, uma panquequinha nordestina muito fácil de fazer para servir no café da manhã ou no lanche e encantar a família! Confira agora mesmo!', '["1 ovo", "1 colher de sopa de manteiga", "1/2 xícara (chá) de açúcar", "1/2 xícara (chá) de farinha de trigo", "1 xícara (chá) de leite", "1 pitada de sal", "óleo ou manteiga para untar"]', '["Misture bem os ingredientes até formar uma massa pastosa.", "Faça um bolinho de massa e cubra com manteiga ou óleo untado.", "Em frigideira antiaderente untada com óleo ou manteiga, espalhe porções da massa, formando círculos de 10 a 12 cm de diâmetro.", "Deixe dourar por baixo e vire para dourar do outro lado.", "Sirva com mel, frutas, geleia, creme de avelã etc."]', true, 'Doces', '["Cearense"]', '10 minutos', '2 porções', 5, true, '2026-03-26 13:53:31.141952', '2026-03-26 16:53:31.126');
INSERT INTO public.recipes VALUES (2, 'macarrao-carbonara', false, 'pasta-g6a3a00a95_1920', 'Macarrão carbonara', 'Receita de Macarrão Carbonara tradicional e deliciosa, feita com bacon, macarrão inegral muito queijo.', '["150 g de bacon em tiras finas de 1 cm", "400 g de macarrão integral", "6 gemas de ovo", "100 g queijo parmesão fresco ralado", "1 pitada de pimenta do reino moída (eu gosto com bastante pimenta)"]', '["Em uma frigideira de bordas altas, em fogo médio, frite as tiras de bacon dos dois lados, tomando cuidado para não queimar.Reserve.", "Em uma frigideira, coloque o bacon, o Spaghetti e o queijo ralado.", "Em outra panela, ferva 3 litros de água e coloque o macarrão para cozinhar (não é necessário adicionar sal ou óleo).", "Cozinhe-o por cerca de 9 minutos, até ficar “al dente”.", "Retire do fogo e reserve.", "Enquanto o macarrão cozinha, despeje as gemas em uma tigela, uma parte do queijo parmesão e a pimenta, misturando tudo com um batedor de arame.", "Adicione duas colheres de sopa da água do cozimento do macarrão para ficar bem cremoso.", "Quando o macarrão estiver “al dente”, escorra-o, aqueça a frigideira com o bacon em fogo baixo e adicione a massa, misturando bem e rapidamente.", "Tire a frigideira do fogo e junte a mistura de gema e queijo, incorporando-a vigorosamente.", "Sirva imediatamente com o restante do queijo ralado por cima."]', false, 'Massas', '["Italiana"]', '30 minutos', '5 porções', 2, false, '2026-03-26 13:53:31.15755', '2026-03-26 16:53:31.156');
INSERT INTO public.recipes VALUES (3, 'caponata-de-beringela', false, 'caponata', 'Caponata de beringela', 'Receita de Caponata de Berinjela deliciosa feita com pimentão amarelo, verde e vermelho, berinjela e champignon .', '["2 berinjelas grandes em cubos", "1 pimentão amarelo em cubos", "1 pimentão vermelho em cubos", "1 cebola grande, em cubos", "1/2 xícara (chá) de azeitonas sem caroço, cortadas ao meio", "Sal a gosto", "Orégano a gosto", "200g de champignon cortado", "Azeite para refogar e para cobrir a conserva", "Salsinha e cebolinha a gosto"]', '["Descasque as berinjelas e corte-as em cubinhos ou tirinhas.", "Tire as sementes dos pimentões e corte-os em cubinhos ou tirinhas.", "Em uma panela, refogue a cebola picadinha junto com o alho amassado e o orégano no azeite.", "Junte a berinjela e os pimentões.", "Mexa para não pegar no fundo.", "Acrescente as azeitonas e o champignon.", "Prove e acerte o sal se necessário.", "Depois que a berinjela estiver bem molinha, apague o fogo e acrescente a salsinha e a cebolinha.", "Coloque em um refratário de vidro e deixe esfriar.", "Esterelize um pote de vidro (com tampa) jogando água fervente dentro dele.", "Depois que esfriar, coloque a caponata no pote de vidro, cubra com azeite, tampe e leve à geladeira.", "Depois que estiver gelada já pode consumir, porém ela fica mais gostosa no dia seguinte.", "Ideal para servir como aperitivo com torradinhas ou pão italiano."]', true, 'Entradas', '["Italiana"]', '40 minutos', '10 porções', 0, false, '2026-03-26 13:53:31.159854', '2026-03-26 16:53:31.159');
INSERT INTO public.recipes VALUES (4, 'costelinha-suina-ao-molho-barbecue', false, 'costela-barbecue', 'Costelinha suina ao molho barbecue', 'A receita daquela costelinha macia feita no forno', '["700g de costelinha suína", "Molho barbecue", "Sal a gosto", "Papel aluminio para cobrir"]', '["Corte no meio para distruibuir bem na assadeira", "Salgue bem, eu gosto com muito sal.", "Coloque na panela de pressão por 7 minutos quando pegar pressão, com água suficiente para cobrir.", "Vá ligando o forno em 200°.", "Retire a carne e coloque na assadeira", "Cubra com papel alumínio e deixe assar por 40 minutos", "Retire o papel alumínio e volte para o forno a assadeira por mais 10 minutos", "Passe bastante molho e cobre novamente com papel alumínio. Leve ao forno por mas 10 minutos", "Tire o papel alumínio e passe mais molho. Leve ao forno por mais 10 minutos", "Passe mais molho, cubra com papel e deixe no forno por mais 10 minutos"]', false, 'Carnes', '["Brasileira"]', '90 minutos', '8 porções', 4, true, '2026-03-26 13:53:31.161011', '2026-03-26 16:53:31.16');
INSERT INTO public.recipes VALUES (5, 'torta-de-frango', false, 'torta-frango', 'Torta de frango', 'Uma deliciosa torta de frango na massa de empada super fácil de fazer.', '["800g de peito de frango", "1 copo de requeijão", "1 molho de tomate", "1 caixa de creme de leite", "Sal e oregano", "3/4 de um pacote de farinha de trigo", "Leite para dar o ponto", "2 colheres cheias de manteiga", "1 colher de fermento em pó"]', '["Cozinhe o peito de frango e disfie, eu prefiro fazer isso na panela de pressão.", "Em seguida adicione um pouco da água de cozimento, o sal, o oregano e o moho de tomate. Deixe a água secar, o frango deve ficar cremoso.", "Ao desligar o fogo acrescente o creme de leite e reserve.", "Para a massa junte a farinha de trigo, os ovos, a manteiga, o sal, o creme de leite e o fermento em um recipiente e sove ate a massa ficar fofa e amarelinha.", "Junte aos poucos o leite para deixar a massa homogênea.", "Divida a massa em duas partes, a primeira parte vai cobrir a assadeira e a segunda será usada para ''fechar'' a torta.", "Abra a primeira parte na assadeira e coloque o frango.", "Em seguida adicione várias colheres de requeijão bem distribuídas.", "Feche a torta com a segunda parte da massa.", "Utilize uma gema de ovo para pincelar sobre a torta.", "Leve ao forno por aproximadamente 50 minutos"]', false, 'Aves', '["Brasileira"]', '90 minutos', '12 porções', 2, false, '2026-03-26 13:53:31.163185', '2026-03-26 16:53:31.162');
INSERT INTO public.recipes VALUES (6, 'bolo-indiano', false, 'bolo-indiano', 'Bolo indiano', 'Uma ótima receita para aquele café da tarde. Um bolo de farinha de rosca diferente de qualquer bolo que você já provou.', '["8 ovos", "100g de manteiga sem sal", "1 xícara e 1/2 de chá de açúcar", "2 xícaras de chá de farinha de rosca", "1 colher de sopa de canela", "1 colher de sopa de fermento químico", "Açucar de confeiteiro com canela para peneirar", "1 lata de leite condensado", "1 colher de sopa de manteiga"]', '["Bata as claras em neve e reserve.", "Na batedeira, bata a margarina com o açúcar e 6 gemas até virar um creme.", "Sem bater, misture a farinha de rosca, a canela e o fermento.", "Delicadamente, incorpore a clara em neve.", "Despeje em fôrma retangular untada e enfarinhada.", "Leve ao forno médio preaquecido (180 ºC) por cerca de 40 minutos ou até dourar.", "Desenforme morno e deixe esfriar.", "Em seguida para o recheio adicione as 2 gemas que sobraram com o leite condensado e a colher de manteiga.", "Misture ate engrossar.", "Jogue por cima do bolo, eu uso uma forma com um furo no meio e deixo um bolo vulcão.", "Jogue o açúcar com canela por cima."]', false, 'Doces', '["Indiana"]', '90 minutos', '10 porções', 10, true, '2026-03-26 13:53:31.164927', '2026-03-26 16:53:31.164');
INSERT INTO public.recipes VALUES (7, 'macarrao-alla-matriciana', false, 'macarrão-amatriciana', 'Macarrão alla matriciana', 'Uma massa de rápido preparo e muito saborosa. E o mais importante: muuuito bacon.', '["300 g de macarrão", "200 g de bacon", "4 tomates grandes e maduros", "1/2 taça de vinho branco seco", "1 colher de sopa de azeite", "1 colher de sopa de fermento químico", "2 colheres de sopa de massa de tomate", "Sal, pimenta e ervas a gosto"]', '["Tire a pele dos tomates corte - os em cubos.", "Em uma panela coloque os tomates e tempere com sal e pimenta.", "Depois de macios, acrescente o purê de tomates, o vinho e, se necessário, um pouquinho de água.", "Espere 5 minutos até o álcool do vinho evaporar.", "Em outra panela, doure o bacon com a colher de azeite.", "Retire o excesso de gordura, e junte ao molho já encorpado.", "Acrescente as ervas secas.", "Adicione ao macarrão ao dente", "Decore com queijo parmesão ralado e um pouco de majericão."]', false, 'Massas', '["Italiana"]', '30 minutos', '3 porções', 10, false, '2026-03-26 13:53:31.167122', '2026-03-26 16:53:31.166');
INSERT INTO public.recipes VALUES (8, 'bolo-prestigio', false, 'bolo-prestigio', 'Bolo prestígio', 'Inspirado pelo chocolade de coco famoso, esse bolo é uma bomba de açúcar.', '["3 ovos", "1/2 xícara (chá) de óleo", "1 xícara (chá) de leite", "1 xícara (chá) de leite", "1 xícara (chá) de chocolate em pó", "2 xícaras (chá) de farinha de trigo", "1 colher (sopa) de fermento", "coco ralado a gosto", "CALDA", "1 garrafa de leite de coco", "1 xícara (chá) de leite", "3 colheres (sopa) de açúcar", "RECHEIO", "1 lata de leite condensado", "1 colher (sopa) de margarina", "100 g de coco ralado", "COBERTURA", "3 colheres (sopa) de margarina", "8 colheres (sopa) de açúcar", "2 colheres (sopa) de chocolate em pó", "2 xícaras (chá) de leite"]', '["BOLO", "Bata no liquidificador, os ovos, o óleo e o leite por 3 minutos e reserve.", "Em um recipiente, misture o açúcar, o trigo, o fermento, o chocolate e o coco ralado a gosto.", "Despeje sobre a mistura do liquidificador e mexa até que a massa fique consistente.", "Despeje a massa em uma forma untada e leve ao forno médio, preaquecido, por 30 minutos ou até que ao enfiar um garfo, este saia limpo.", "Deixe esfriar, corte ao meio e reserve.", "CALDA", "Deixe esfriar, corte ao meio e reserve.", "RECHEIO", "Em uma panela, leve o leite condensado, a margarina e o coco ralado ao fogo até desgrudar do fundo e recheie o bolo.", "Cubra com a outra metade da massa, faça alguns furos com o garfo e despeje mais calda.", "COBERTURA", "Leve a margarina, o açúcar, o chocolate em pó e o leite ao fogo até obter uma consistência firme e cubra o bolo.", "Leve a geladeira por aproximadamente 45 minutos."]', false, 'Doces', '["Brasileira"]', '120 minutos', '3 porções', 4, false, '2026-03-26 13:53:31.168174', '2026-03-26 16:53:31.167');
INSERT INTO public.recipes VALUES (9, 'molho-barbecue', false, 'barbecue', 'Molho barbecue', 'Uma receita de barbecue caseira. Esse molho cremoso vai ser o sucesso do churrasco.', '["350g de ketchup", "4 colheres de sopa de molho inglês", "2 colheres de sopa de mostarda", "3 colheres de sopa de açúcar mascavo", "1 colher de sopa de vinagre branco", "2 colheres de sopa de azeite de oliva", "1/2 cebola picadinha", "1 colher de chá de pimenta calabresa", "1 colher de chá de pimenta do reino", "sal"]', '["Refogue a cebola no azeite ate dourar.", "Em seguida acrescente os igredientes (exceto a pimenta e o sal) e cozinhe em fogo baixo durante 20min ou ate reduzir, mexendo de vez enquanto", "É necessário respeitar esse tempo para que o sabor dos igredientes fique mais intenso", "Desligue o fogo, prove e tempere a gosto com pimenta do reino e sal.", "Após esfriar bata no liquidificador até obter um molho cremoso e homogêneo"]', false, 'Molhos', '["Brasileira"]', '40 minutos', '10 porções', 4, false, '2026-03-26 13:53:31.171653', '2026-03-26 16:53:31.17');
INSERT INTO public.recipes VALUES (10, 'bolo-de-requeijao', false, 'requeijao', 'Bolo de requeijão', 'Um bolo que vai na geladeira, feito com requeijão e leite condensado. Fica uma delicia', '["250g de requeijão", "1 lata de leite condensado", "1 lata de leite de vaca", "1 colher de sopa de maizena", "1 colher de sopa de manteiga", "4 gemas de ovos"]', '["Bater tudo no liquidificador, menos as claras de ovos, bater separadamente.", "Depois juntar tudo.", "Assar em forno médio, preaquecido, por 25 minutos.", "Levar para gelar."]', false, 'Doces', '["Brasileira"]', '40 minutos', '10 porções', 15, false, '2026-03-26 13:53:31.172902', '2026-03-26 16:53:31.172');
INSERT INTO public.recipes VALUES (11, 'molho-pesto', false, 'pesto', 'Molho pesto', 'O incrível molho pesto pode servir de acompanhamento para sopa, ovos mexidos e grelhados. Como se não bastasse, ele ainda é um molho rápido e delicioso de macarrão. ', '["1 dente de alho descascado", "½ xícara (chá) de folhas de manjericão fresco", "2 nozes (eu troco por castanha de caju)", "2 colheres (sopa) de queijo parmesão ralado", "¼ de xícara (chá) de azeite", "sal e pimenta-do-reino moída na hora a gosto"]', '["No processador, triture os ingredientes, adicionando na seguinte ordem: alho com uma pitada de sal, folhas de manjericão, nozes, queijo e, por último, misture o azeite. Tempere com sal e pimenta-do-reino e sirva a seguir.", "Tempere com um pouco de pimenta-do-reino e sirva a seguir."]', false, 'Molhos', '["Italiana"]', '20 minutos', '4 porções', 1, true, '2026-03-26 13:53:31.175099', '2026-03-26 16:53:31.174');
INSERT INTO public.recipes VALUES (12, 'risoto-de-bacon', false, 'risoto-bacon', 'Risoto de bacon', 'Risoto de bacon com parmesão. Aquela receita que é unanimidade entre todos os fãs de bacon.', '["1 ½ xícaras de arroz arbóreo", "3 colheres de manteiga", "1 cebola média picada", "1 cálice de vinho branco seco", "150g de bacon picado (sem pele)", "1 caldo de bacon", "4 xícaras de água", "100g de parmesão ralado"]', '["Em uma panela de fundo grosso coloque o bacon (se quiser acrescente um fio de óleo), frite até ficar bem torrado.", "Com o auxílio de uma escumadeira, retire o bacon da gordura e reserve (pode pegar um pouco da gordura).", "À parte, ferva a água e dissolva o caldo de bacon.", "Em uma panela também de fundo grosso aqueça 2 colheres de manteiga, coloque a cebola e deixe ficar transparente.", "Acresente o bacon, o arroz e o vinho. Aguarde o vinho evaporar", "Acrescente aos poucos (½ xícara aproximadamente por vez) o caldo de bacon reservado, mexendo sempre.", "Quando terminar o caldo verifique se o arroz está al dente, caso contrário, acrescente um pouco de água fervente até dar ponto.", "Atenção, o risoto não deve passar MAIS de 20 minutos ate ficar pronto.", "Desligue o fogo.", "Adicione uma colher de manteiga e o parmesão ralado e mecha tudo.", "Ao desligar o fogo acrescente o creme de leite e reserve.", "Deixe um pouco do parmesão para decorar"]', false, 'Risotos', '["Italiana"]', '35 minutos', '4 porções', 18, false, '2026-03-26 13:53:31.176084', '2026-03-26 16:53:31.175');
INSERT INTO public.recipes VALUES (13, 'pipoca-de-frango-na-air-fryer', false, 'pipoca-frango', 'Pipoca de frango na air fryer', 'Um gostoso petisco de frango ótimo para tira gosto ou lanche.', '["300g de peito de frango", "Sal", "Páprica defumada", "Azeite", "Amido de milho"]', '["Corte o frango em cubinhos pequenos.", "Tempre com sal, a páprica e azeite.", "Adicione o amido de milho e misture ate que o frango fique envolto no amido.", "Deixe por 12 minutos a 200°."]', false, 'Aves', '["Boteco"]', '15 minutos', '4 porções', 18, false, '2026-03-26 13:53:31.178187', '2026-03-26 16:53:31.177');
INSERT INTO public.recipes VALUES (14, 'pave-de-ouro-branco', false, 'pave-ouro-branco', 'Pavê de ouro branco', 'Uma deliciosa sobremesa fácil de fazer e deliciosa de comer.', '["1 latas de leite condensado", "2 caixas de creme de leite", "200g de chorolate meio amargo", "200g de chocolate branco (aqui costumo comprar uma barra do branco e uma do Opereta)", "2 colheres de sopa de manteiga", "15 unidades de ouro braco", "Biscoito maizena", "Leite"]', '["Derreta o chocolate meio amargo no microondas ou em banho maria", "Adicione o chocolate derretido em uma panela com manteiga, meia lata de leite condensado e uma caixa de creme de leite", "Leve ao fogo baixo e mecha ate ele dar o ponto do brigadeiro", "Derreta o chocolate branco no microondas ou em banho maria", "Adicione o chocolate derretido em uma panela com manteiga, meia lata de leite condensado e uma caixa de creme de leite", "Leve ao fogo baixo e mecha ate ele dar o ponto do brigadeiro", "Coloque uma ''cama'' de biscoitos no fundo da travessa e molhe com um pouco de leite", "Adicione a camada de chocolate preto", "Coloque mais uma camada de biscoitos e molhe com leite", "Adicine a camada de chocolate branco", "Faça uma farofa com os chocolates ouro branco (eu costumo cortar em 4 partes com uma faca).", "Jogue a farofa por cima do pavê e leve a geladeira por 4 horas ou congelador por 2 horas"]', false, 'Doces', '["Brasileira"]', '40 minutos', '8 porções', 18, false, '2026-03-26 13:53:31.179214', '2026-03-26 16:53:31.178');
INSERT INTO public.recipes VALUES (16, 'teste-de-receita', true, '/uploads/240927-pf-observatorio-ia-web-1-1111c2a4-73a8-49e9-9de9-4d38bfdeb4f1.jpg', 'teste de receita', 'adsfadsfasdfasdfasdfadsf', '["BrasileiraBrasileira", "Brasileira", "Brasileira", "Brasileira", "BrasileiraBrasileiraBrasileira"]', '["BrasileiraBrasileira", "Brasileira", "BrasileiraBrasileiraBrasileira", "Brasileira", "BrasileiraBrasileiraBrasileiraBrasileira"]', false, 'Doces', '["Brasileira"]', '15 minutos', '2 porcoes', 0, false, '2026-03-26 14:18:26.479738', '2026-03-26 17:19:47.482');
INSERT INTO public.recipes VALUES (15, 'frango-oriental', false, 'frango-com-legumes', 'Frango oriental', 'Deliciosa receita de Frango com legumes, simples e fácil de se fazer!', '["3 filés de peito de frango", "2 pimentões grandes (um verde e um vemelho)", "1 cebola média", "1 xícara de chá de couve-flor", "1 xícara de chá de cenoura", "2 xícaras de chá de brocolis frecos picados", "2 colheres de sopa de azeite de oliva", "1 e 1/2 dente de alho picado", "2 colheres de sopa de mel", "3 colheres de sopa de shoyu", "Sala gosto", "1 colher de vinagre de maçã"]', '["Fatie em tiras os pimentões, a cebola e a cenoura", "Em uma frigideira ou em uma panela grande, coloque o azeite, a cebola e o alho e refogue em fogo baixo", "Quando a cebola ficar transparente, adicione os pimentões, a cenoura, a couve-flor e o brócolis", "Corte o frango em cubos ou em pequenas tiras e tempere à sua maneira", "Em outra panela, refogue o frango até que fique completamente cozido/frito", "Deixe dourar e adicione o shoyu", "Junte o frango com os legumes, adicione o vinagre de maçã e o mel", "Misture bem, deixe dourar e desligue o fogo", "Sirva e bom apetite!"]', false, 'Aves', '["Orienal"]', '40 minutos', '8 porcoes', 19, false, '2026-03-26 13:53:31.181486', '2026-03-26 18:12:43.661');
INSERT INTO public.recipes VALUES (17, 'macarrao-ao-alho-e-oleo-com-brocolis-e-tomates-confit', false, 'https://i0.wp.com/porkworld.com.br/wp-content/uploads/2025/05/receita-de-macarrao-ao-alho-e-oleo-com-bacon-e-brocolis.png?fit=1200%2C675&ssl=1', 'Macarrão ao Alho e Óleo com Brócolis e Tomates Confit', 'Uma versão especial do clássico macarrão ao alho e óleo, incrementada com brócolis crocantes e tomates confit que explodem em sabor. Simples, rápida e perfeita para um jantar durante a semana.

', '["500g de macarrão (espaguete ou penne)", "1 cabeça de brócolis (apenas os floretes)", "2 tomates maduros cortados em cubos", "8 dentes de alho fatiados", "1/2 xícara de azeite de oliva extra virgem", "Sal a gosto", "Pimenta-do-reino moída na hora a gosto", "Queijo parmesão ralado para finalizar", "Salsinha picada para decorar"]', '["Cozinhe o macarrão em água fervente com sal até ficar al dente. Reserve 1 xícara da água do cozimento.", "Enquanto isso, aqueça metade do azeite em uma frigideira grande e refogue os floretes de brócolis até ficarem levemente dourados e crocantes. Reserve.", "Na mesma frigideira, adicione o restante do azeite e os alhos fatiados. Refogue em fogo baixo até dourar levemente, cuidado para não queimar.", "Adicione os tomates e cozinhe por 2 minutos até começarem a desmanchar.", "Escorra o macarrão e transfira para a frigideira com o molho. Misture bem.", "Adicione os brócolis reservados e a água do cozimento se necessário para dar cremosidade.", "Tempere com sal e pimenta a gosto.", "Sirva imediatamente com queijo parmesão ralado e salsinha picada por cima."]', true, 'Massa', '["Italiana"]', '25 minutos', '4 porcoes', 0, false, '2026-03-26 15:24:20.299965', '2026-03-26 18:24:20.298');


--
-- Name: __drizzle_migrations_id_seq; Type: SEQUENCE SET; Schema: drizzle; Owner: postgres
--

SELECT pg_catalog.setval('drizzle.__drizzle_migrations_id_seq', 1, true);


--
-- Name: recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recipes_id_seq', 17, true);


--
-- PostgreSQL database dump complete
--

\unrestrict ZIbt2GzRwbssAmEgBeYKEfELVWg6Sz3zFHdKJUGCyT23mP2C0GOGTLnNDAI5Hxa

